version: '3.1'

services:
  mongo:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: xy
      MONGO_INITDB_ROOT_PASSWORD: XY@dev1024
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./eproject-verison-init.js:/docker-entrypoint-initdb.d/1_eproject-verison-init.js:ro

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: xy
      ME_CONFIG_MONGODB_ADMINPASSWORD: XY@dev1024