

---

spring:
  profiles: dev

eproject:
  db:
    host: me
    port: 27017
    domain: ${eproject.db.host}:${eproject.db.port}
  auth:
    domain: me:8080
    context-path: /uaa
  admin:
    domain: me:2333
  eureka:
    domain: me:2335

logging:
  level:
    ROOT: DEBUG
    org.springframework.data.mongodb: DEBUG


---

spring:
  profiles: test

eproject:
  db:
    host: mongo.eproject.com
    port: 27017
    domain: ${eproject.db.host}:${eproject.db.port}
  auth:
    domain: auth.eproject.com:16666
    context-path:
  admin:
    domain: admin.eproject.com:2333
  eureka:
    domain: eureka.eproject.com:2335

logging:
  level:
    ROOT: INFO


---

spring:
  profiles: prod

eproject:
  db:
    host: mongodb.eproject.com
    port: 27017
    domain: ${eproject.db.host}:${eproject.db.port}
  auth:
    domain: auth.eproject.com:16666
    context-path:
  admin:
    domain: admin.eproject.com:2333
  eureka:
    domain: eureka.eproject.com:2335


---

spring:
  profiles: docker

eproject:
  db:
    host: eproject-mongodb
    port: 27017
    domain: ${eproject.db.host}:${eproject.db.port}
  auth:
    domain: auth.eproject.com:16666
    context-path:
  admin:
    domain: eproject-admin:2333
  eureka:
    domain: eproject-eureka:2335


---

server:
  port: 2340

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: eProject-Version
  boot:
    admin:
      client:
        url: http://${eproject.admin.domain}/admin-service
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
          service-path: ${spring.webflux.base-path}
  webflux:
    base-path: /version-service
  data:
    mongodb:
      username: xy
      password: XY@dev1024
      host: ${eproject.db.host}
      port: ${eproject.db.port}
      database: eproject-version
  security:
    user:
      roles: ACTUATOR,DEV
      name: dev
      password: XY@dev1024
    oauth2:
      client:
        registration:
          auth-sso:
            provider: uaa
            client-id: eProject-Version
            client-secret: version123
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/"
            client-name: sso
            scope:
              - openid
              - version.admin
          auth-client-auth-code:
            provider: uaa
            client-id: eProject-Version
            client-secret: version123
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
            client-name: authorization_code
            scope:
              - openid
              - version.read
          auth-client-implicit:
            provider: uaa
            client-id: eProject-Version
            client-secret: version123
            authorization-grant-type: implicit
            #set to UI html
            redirect-uri: "{baseUrl}/token.html"
            client-name: implicit
            scope:
              - openid
              - version.read
          auth-client-client-creds:
            provider: uaa
            client-id: eProject-Version
            client-secret: version123
            authorization-grant-type: client_credentials
            client-name: client_credentials
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
            authority: DEV
          auth-client-password:
            provider: uaa
            client-id: eProject-Version
            client-secret: version123
            authorization-grant-type: password
            client-name: password
            redirect-uri: "{baseUrl}/login/oauth2/client/{registrationId}"
            scope:
              - openid
              - version.admin
        provider:
          uaa:
#            authorization-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/oauth/authorize
#            token-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/oauth/token
#            jwk-set-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/token_keys
#            user-info-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/userinfo
            user-name-attribute: user_name
            issuer-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/oauth/token
      resourceserver:
        jwt:
          jwk-set-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/token_keys
          issuer-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/oauth/token
        opaquetoken:
          client-id: eProject-Version
          client-secret: version123
          introspection-uri: http://${eproject.auth.domain}${eproject.auth.context-path}/oauth/check_token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eproject.eureka.domain}/eureka-service/eureka

logging:
  level:
    ROOT: ERROR
